---
- name: "Install system packages. (Debian)"
  when: "ansible_facts.os_family == 'Debian'"
  ansible.builtin.apt:
    name: "{{ nginx_system_packages }}"
    update_cache: true
    cache_valid_time: 3600
    state: "present"

- name: "Install system packages. (RedHat)"
  when: "ansible_facts.os_family == 'RedHat'"
  ansible.builtin.dnf:
    name: "{{ nginx_system_packages }}"
    state: "present"
